version: "3"
services:
  broker:
    image: eclipse-mosquitto:1.6
    ports:
      - "9001:9001"
      - "1883:1883"
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=TimeSeries
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    working_dir: /app
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
networks:
  default:
    external:
        name: iot-network
